import "./index-test";
import "./unit/models/country.spec";
import "./unit/models/culture.spec";
import "./models/user";
import "./models/profile";
import "./unit/models/food.spec";
import "./unit/models/music.spec";
import "./unit/models/State.spec";
import "./unit/models/TouristCenter.spec";
