import "./index-test";
import "./models/user";
import "./models/profile";
import "./unit/models/food.spec";
import "./unit/models/music.spec";
import "./unit/models/country.spec";
import "./unit/models/culture.spec";
import "./unit/models/comment.spec";
import "./unit/models/newsletter.spec";
