version: "3.7"
services: 
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: Devcareers
            POSTGRES_DB: know_africa_docker_db
        volumes: 
            - ./pgdata:/var/lib/postgresql/data
        ports: 
            - "5432:5432"
    web:
        image: know-africa
        build: .
        depends_on: 
            - db
        environment: 
            DEV_DATABASE_URL: postgres://postgres:Devcareers@db:5432/know_africa_docker_db
            NODE_ENV: development
            PORT: 3000
        ports: 
            - "80:3000"