# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: NodeJS CI
on: ["push"]

jobs:
  build:
    name: Build
    runs-on: [ windows-latest, linux-latest ]
    strategy:
      matrix:
        node-version: [12.x, 14.x]

  services:
      postgres:
        image: postgis/postgis:10-2.5
        env:
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  
  steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm run coverage

    - name: Import DB seed data
        run: psql -d postgresql://postgres:admin@localhost:5432/test_db
        working-directory: ./src/database/seeders
        env:
          PGPASSWORD: password

      - name: Test some module
        run: npm test
        env:
          CI_DB_URL: postgresql://postgres:admin@localhost:5432/test_db

    - name: Coveralls
      uses: coverallsapp/github-action@master
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        COVERALLS_GIT_BRANCH: ${{ github.ref }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}